name: MLOps pipeline with training and evaluation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Train YOLO Model
        run: python models/yolo26n/train.py

      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v3
        with:
          name: yolo-best-model
          path: outputs/model_weights/model_a_best.pt

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Download trained model artifact
        uses: actions/download-artifact@v3
        with:
          name: yolo-best-model
          path: outputs/model_weights/

      - name: Evaluate YOLO Model
        run: python scripts/evaluate.py